version: '3'

services:

  mongo_server:
    image: 'mongo:latest'
    container_name: "${MONGO_SERVER_CONTAINER_NAME}"
    ports:
      - "${HOST_MONGO_SERVER_PORT}:27017"
    volumes:
      - ./data:/data/db

  mongo_seed:
    container_name: 'mongo_seed'
    build: ./db
    depends_on: 
      - mongo_server

  rest_python3:
    container_name: "${REST_PYTHON3_CONTAINER_NAME}"
    build: ./app
    env_file: 
      ./.env
    depends_on:
     - 'mongo_server'
    ports:
     - "${HOST_FLASK_PORT}:5000"
    volumes:
     - ./app:/app

